[[bin]]
name = 'xplr'

[[bench]]
name = 'criterion'
harness = false
path = './benches/criterion.rs'

[package]
name = 'xplr'
version = '0.21.2'
authors = ['Arijit Basu <hi@arijitbasu.in>']
edition = '2021'
description = 'A hackable, minimal, fast TUI file explorer'
license = 'MIT'
readme = 'README.md'
repository = 'https://github.com/sayanarijit/xplr'
homepage = 'https://xplr.dev'
documentation = 'https://xplr.dev/en'
keywords = ['terminal', 'file', 'explorer', 'manager', 'tui']
categories = ['command-line-interface', 'command-line-utilities']
include = ['src/**/*', 'docs/en/src/**/*', 'LICENSE', 'README.md']

[dependencies]
libc = "0.2.147"
humansize = "2.1.3"
natord = "1.0.9"
anyhow = "1.0.71"
serde_yaml = "0.9.22"
crossterm = { version = "0.26.1", features = [], default-features = false }
ansi-to-tui = "3.1.0"
regex = "1.9.1"
gethostname = "0.4.3"
serde_json = "1.0.102"
path-absolutize = "3.1.0"
which = "4.4.0"
nu-ansi-term = "0.48.0"
textwrap = "0.16"
snailquote = "0.3.1"
skim = { version = "0.10.4", default-features = false }
time = { version = "0.3.23", features = ["serde", "local-offset", "formatting", "macros"] }
jf = "0.6.2"
xdg = "2.5.0"
home = "0.5.5"

[dependencies.lscolors]
version = "0.14.0"
default-features = false
features = ["nu-ansi-term"]

[dependencies.lazy_static]
version = "1.4.0"
default-features = false

[dependencies.mime_guess]
version = "2.0.4"
default-features = false

[dependencies.tui]
version = "0.21.0"
default-features = false
features = ['crossterm', 'serde']
package = 'ratatui'

[dependencies.serde]
version = "1.0.171"
features = []
default-features = false

[dependencies.indexmap]
version = "2.0.0"
features = ['serde']

[dependencies.mlua]
version = "0.8.9"
features = ['lua54', 'vendored', 'serialize', 'send']
default-features = false

[dependencies.tui-input]
version = "0.7.1"
features = ['serde']

[dev-dependencies]
criterion = "0.5.1"
assert_cmd = "2.0.12"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[features]
